spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false
    username: root
    password: Honor46Sql$10
  output:
    ansi.enabled: ALWAYS
  jpa:
    driver: com.mysql.cj.jdbc.Driver
    hibernate:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      show-sql: true
      ddl-auto: update

config:
  prefix:
  agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  webinterface: /admin
  site:
    - url: https://sangria31.ru
      name: што
    - url: http://www.playback.ru/
      name: Тел
    - url: http://astudio.store
      name: шторы
    - url: https://volochek.life/
      name: нов
    - url: https://amelie-shtory.ru
      name: шторы
    - url: https://www.svetlovka.ru/
      name: Светловка
    - url: https://dombulgakova.ru/
      name: Светловка

